"""empty message
Revision ID: 1
Revises:
Create Date: 2023-01-18 14:19:16.347405
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csvjoinmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_name', sa.String(), nullable=True),
    sa.Column('dlvrloadgndvsense0', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end csvjoinmap commands ###

    op.create_table('par_exe_csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_name', sa.String(), nullable=True),
    sa.Column('test', sa.String(), nullable=True),
    sa.Column('flopcnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end par_exe_csv commands ###

    op.create_table('par_exe_mapfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dlvrloadgndvsense0', sa.String(), nullable=True),
    sa.Column('dlvrloadgndvsense02', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end par_exe_mapfile commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###